import type { CapacityPoint, StudyTask } from "@/lib/types";
import { localSchedule } from "@/lib/cognitive-model";

type AgentScheduleInput = {
  googleAccessToken: string;
  tasks: StudyTask[];
  curve: CapacityPoint[];
  startIso: string;
  timezone: string;
};

function extractJson(text: string) {
  const fenced = text.match(/```json\s*([\s\S]*?)```/i)?.[1];
  const raw = fenced ?? text.match(/\{[\s\S]*\}/)?.[0] ?? text;
  return JSON.parse(raw);
}

export async function runSchedulingAgent(input: AgentScheduleInput) {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return {
      source: "local-fallback",
      explanation: "OPENAI_API_KEY is not configured, so a local curve-based schedule was generated.",
      blocks: localSchedule(input.tasks, input.curve, new Date(input.startIso))
    };
  }

  const compactCurve = input.curve
    .filter((_, index) => index % 4 === 0)
    .map((point) => ({ label: point.label, hour: point.hour, score: point.score }));

  const response = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: {
      authorization: `Bearer ${apiKey}`,
      "content-type": "application/json"
    },
    body: JSON.stringify({
      model: process.env.OPENAI_MODEL ?? "gpt-4.1-mini",
      input: [
        {
          role: "system",
          content:
            "You are a cognitive capacity scheduling agent. Use Google Calendar through the MCP connector to inspect existing events. Choose non-conflicting study blocks that match hard tasks to high capacity scores, medium tasks to good scores, and low tasks to lower/review windows. Return only JSON."
        },
        {
          role: "user",
          content: JSON.stringify({
            task: "Create a study schedule for the next 24 hours. If the connector allows calendar event creation, create the study blocks on Google Calendar. Always return JSON with explanation and blocks.",
            timezone: input.timezone,
            startIso: input.startIso,
            tasks: input.tasks,
            capacityCurve: compactCurve,
            expectedJsonShape: {
              explanation: "short string",
              blocks: [
                {
                  task_id: "task id or null",
                  title: "event title",
                  start_at: "ISO datetime",
                  end_at: "ISO datetime",
                  capacity_score: 0,
                  google_event_id: "id if created, otherwise null"
                }
              ]
            }
          })
        }
      ],
      tools: [
        {
          type: "mcp",
          server_label: "google_calendar",
          connector_id: "connector_googlecalendar",
          authorization: input.googleAccessToken
        }
      ]
    })
  });

  if (!response.ok) {
    const errorText = await response.text();
    return {
      source: "local-fallback",
      explanation: `OpenAI scheduling was unavailable, so a local curve-based schedule was generated. ${errorText.slice(0, 220)}`,
      blocks: localSchedule(input.tasks, input.curve, new Date(input.startIso))
    };
  }

  const data = await response.json();
  const outputText =
    data.output_text ??
    data.output
      ?.flatMap((item: { content?: { text?: string }[] }) => item.content ?? [])
      .map((content: { text?: string }) => content.text ?? "")
      .join("\n");

  const parsed = extractJson(outputText || "{}");

  return {
    source: "openai-mcp",
    explanation: parsed.explanation ?? "Schedule generated by the OpenAI agent with Google Calendar MCP.",
    blocks: Array.isArray(parsed.blocks) ? parsed.blocks : []
  };
}
