import type { CapacityPoint, StudyTask } from "@/lib/types";
import { localSchedule } from "@/lib/cognitive-model";

type AgentScheduleInput = {
  googleAccessToken: string;
  tasks: StudyTask[];
  curve: CapacityPoint[];
  startIso: string;
  timezone: string;
};

type CalendarTaskGenerationInput = {
  googleAccessToken: string;
  timezone: string;
  existingTasks: StudyTask[];
};

function extractJson(text: string) {
  const fenced = text.match(/```json\s*([\s\S]*?)```/i)?.[1];
  const raw = fenced ?? text.match(/\{[\s\S]*\}/)?.[0] ?? text;
  return JSON.parse(raw);
}

function responseOutputText(data: {
  output_text?: string;
  output?: Array<{ content?: Array<{ text?: string }> }>;
}) {
  return (
    data.output_text ??
    data.output
      ?.flatMap((item) => item.content ?? [])
      .map((content) => content.text ?? "")
      .join("\n") ??
    ""
  );
}

function openAiFallbackExplanation(status: number, errorText: string) {
  const normalizedError = errorText.toLowerCase();

  if (status === 429 && normalizedError.includes("quota")) {
    return "OpenAI API quota is unavailable. Add API billing credits or raise the project spending limit to enable calendar-aware AI scheduling. A local curve-based schedule was generated instead.";
  }

  if (status === 429) {
    return "OpenAI API rate limits were reached. Try scheduling again shortly. A local curve-based schedule was generated instead.";
  }

  if (status === 401) {
    return "The OpenAI API key was rejected. Replace OPENAI_API_KEY with an active project API key. A local curve-based schedule was generated instead.";
  }

  return "OpenAI scheduling is temporarily unavailable. A local curve-based schedule was generated instead.";
}

export async function runSchedulingAgent(input: AgentScheduleInput) {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return {
      source: "local-fallback",
      explanation: "OPENAI_API_KEY is not configured, so a local curve-based schedule was generated.",
      blocks: localSchedule(input.tasks, input.curve, new Date(input.startIso))
    };
  }

  const compactCurve = input.curve
    .filter((_, index) => index % 4 === 0)
    .map((point) => ({ label: point.label, hour: point.hour, score: point.score }));

  const response = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: {
      authorization: `Bearer ${apiKey}`,
      "content-type": "application/json"
    },
    body: JSON.stringify({
      model: process.env.OPENAI_MODEL ?? "gpt-4.1-mini",
      input: [
        {
          role: "system",
          content:
            "You are a cognitive capacity scheduling agent. Use Google Calendar through the MCP connector to inspect existing events. Choose non-conflicting study blocks that match hard tasks to high capacity scores, medium tasks to good scores, and low tasks to lower/review windows. Return only JSON."
        },
        {
          role: "user",
          content: JSON.stringify({
            task: "Create a study schedule for the next 24 hours. If the connector allows calendar event creation, create the study blocks on Google Calendar. Always return JSON with explanation and blocks.",
            timezone: input.timezone,
            startIso: input.startIso,
            tasks: input.tasks,
            capacityCurve: compactCurve,
            expectedJsonShape: {
              explanation: "short string",
              blocks: [
                {
                  task_id: "task id or null",
                  title: "event title",
                  start_at: "ISO datetime",
                  end_at: "ISO datetime",
                  capacity_score: 0,
                  google_event_id: "id if created, otherwise null"
                }
              ]
            }
          })
        }
      ],
      tools: [
        {
          type: "mcp",
          server_label: "google_calendar",
          connector_id: "connector_googlecalendar",
          authorization: input.googleAccessToken,
          require_approval: "never"
        }
      ]
    })
  });

  if (!response.ok) {
    const errorText = await response.text();
    return {
      source: "local-fallback",
      explanation: openAiFallbackExplanation(response.status, errorText),
      blocks: localSchedule(input.tasks, input.curve, new Date(input.startIso))
    };
  }

  const data = await response.json();
  const parsed = extractJson(responseOutputText(data) || "{}");

  const blocks = Array.isArray(parsed.blocks) ? parsed.blocks : [];
  if (blocks.length === 0 && input.tasks.length > 0) {
    return {
      source: "local-fallback",
      explanation:
        "OpenAI connected to Google Calendar but did not return study blocks. A local curve-based schedule was generated instead.",
      blocks: localSchedule(input.tasks, input.curve, new Date(input.startIso))
    };
  }

  return {
    source: "openai-mcp",
    explanation: parsed.explanation ?? "Schedule generated by the OpenAI agent with Google Calendar MCP.",
    blocks
  };
}

export async function runCalendarTaskGenerationAgent(input: CalendarTaskGenerationInput) {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    throw new Error("OPENAI_API_KEY is not configured.");
  }

  const response = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: {
      authorization: `Bearer ${apiKey}`,
      "content-type": "application/json"
    },
    body: JSON.stringify({
      model: process.env.OPENAI_MODEL ?? "gpt-4.1-mini",
      input: [
        {
          role: "system",
          content:
            "You are a study planning assistant. Inspect Google Calendar for the next 14 days. Infer useful preparation tasks only from study, class, exam, assessment, assignment, project, and deadline events. Do not create or modify calendar events. Avoid duplicates and return only JSON."
        },
        {
          role: "user",
          content: JSON.stringify({
            task:
              "Generate up to 6 actionable study tasks based on relevant upcoming calendar events. Use concise titles. Estimate realistic minutes and difficulty. Set due_at before the related event when possible. Return an empty array when no relevant events exist.",
            timezone: input.timezone,
            existingTasks: input.existingTasks.map((task) => ({
              title: task.title,
              due_at: task.due_at ?? null
            })),
            expectedJsonShape: {
              explanation: "short string",
              tasks: [
                {
                  title: "task title",
                  description: "why this preparation task was inferred",
                  difficulty: "low | medium | high",
                  estimated_minutes: 60,
                  due_at: "ISO datetime or null"
                }
              ]
            }
          })
        }
      ],
      tools: [
        {
          type: "mcp",
          server_label: "google_calendar",
          connector_id: "connector_googlecalendar",
          authorization: input.googleAccessToken,
          require_approval: "never"
        }
      ]
    })
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(openAiFallbackExplanation(response.status, errorText).replace(" A local curve-based schedule was generated instead.", ""));
  }

  const data = await response.json();
  const parsed = extractJson(responseOutputText(data) || "{}");

  return {
    source: "openai-mcp",
    explanation: parsed.explanation ?? "Calendar review completed.",
    tasks: Array.isArray(parsed.tasks) ? parsed.tasks : []
  };
}
